# Generated by Django 3.0.3 on 2020-03-05 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apaterno', models.CharField(max_length=35)),
                ('amaterno', models.CharField(max_length=35)),
                ('curp', models.CharField(db_column='CURP', max_length=18)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('no_ss', models.CharField(blank=True, max_length=15, null=True)),
                ('usuario', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=45)),
                ('correo_electronico', models.CharField(max_length=45)),
                ('nfc_data', models.TextField(blank=True, db_column='NFC_data', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empleado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LugarCompra',
            fields=[
                ('idlugar_compra', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tienda', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'lugar_compra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('idpaquete', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('duracion_estimada', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paquete',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lavado',
            fields=[
                ('idlavado', models.AutoField(primary_key=True, serialize=False)),
                ('placas', models.CharField(max_length=5)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('lote', models.IntegerField(blank=True, null=True)),
                ('empleado_idempleado', models.ForeignKey(db_column='empleado_idempleado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='empleado_idempleado', to='lavado.Empleado')),
                ('encargado_idempleado', models.ForeignKey(db_column='encargado_idempleado', on_delete=django.db.models.deletion.DO_NOTHING, to='lavado.Empleado')),
                ('paquete_idpaquete', models.ForeignKey(db_column='paquete_idpaquete', on_delete=django.db.models.deletion.DO_NOTHING, to='lavado.Paquete')),
                ('supervisor_idempleado', models.ForeignKey(db_column='supervisor_idempleado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervisor_idempleado', to='lavado.Empleado')),
            ],
            options={
                'db_table': 'lavado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('idarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('codigo_barras', models.CharField(blank=True, max_length=30, null=True)),
                ('lugar_compra_idlugar_compra', models.ForeignKey(db_column='lugar_compra_idlugar_compra', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='lavado.LugarCompra')),
            ],
            options={
                'db_table': 'articulo',
                'managed': True,
            },
        ),
    ]
