-- MySQL Script generated by MySQL Workbench
-- Tue 03 Mar 2020 07:30:18 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema is
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema is
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `is` DEFAULT CHARACTER SET latin1 ;
USE `is` ;

-- -----------------------------------------------------
-- Table `is`.`lugar_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`lugar_compra` (
  `idlugar_compra` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_tienda` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlugar_compra`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1
COMMENT = '\n';


-- -----------------------------------------------------
-- Table `is`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`articulo` (
  `idarticulo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `codigo_barras` VARCHAR(30) NULL DEFAULT NULL,
  `lugar_compra_idlugar_compra` INT(11) NOT NULL,
  PRIMARY KEY (`idarticulo`),
  INDEX `fk_articulo_lugar_compra1_idx` (`lugar_compra_idlugar_compra` ASC),
  CONSTRAINT `fk_articulo_lugar_compra1`
    FOREIGN KEY (`lugar_compra_idlugar_compra`)
    REFERENCES `is`.`lugar_compra` (`idlugar_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`auth_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`django_content_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`auth_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT(11) NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC),
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `is`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`auth_group_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC),
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC),
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `is`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `is`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`auth_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`auth_user_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC),
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC),
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `is`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `is`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`auth_user_user_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC),
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC),
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `is`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `is`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`django_admin_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT(5) UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC),
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC),
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `is`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `is`.`auth_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`django_migrations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`rol_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`rol_empleado` (
  `idrol_empleado` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(10) NOT NULL,
  `privilegios` INT(11) NOT NULL,
  PRIMARY KEY (`idrol_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`empleado` (
  `idempleado` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(35) NOT NULL,
  `apaterno` VARCHAR(35) NOT NULL,
  `amaterno` VARCHAR(35) NOT NULL,
  `CURP` VARCHAR(18) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `activo` TINYINT(4) NOT NULL,
  `no_ss` VARCHAR(15) NULL DEFAULT NULL,
  `usuario` VARCHAR(10) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `correo_electronico` VARCHAR(45) NOT NULL,
  `NFC_data` BLOB NULL DEFAULT NULL,
  `rol_empleado_idrol_empleado` INT(11) NOT NULL,
  PRIMARY KEY (`idempleado`),
  INDEX `fk_empleado_rol_empleado1_idx` (`rol_empleado_idrol_empleado` ASC),
  CONSTRAINT `fk_empleado_rol_empleado1`
    FOREIGN KEY (`rol_empleado_idrol_empleado`)
    REFERENCES `is`.`rol_empleado` (`idrol_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`paquete` (
  `idpaquete` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(15) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `precio` FLOAT NOT NULL,
  `duracion_estimada` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`idpaquete`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`lavado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`lavado` (
  `idlavado` INT(11) NOT NULL AUTO_INCREMENT,
  `placas` VARCHAR(5) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_termino` TIME NOT NULL,
  `lote` INT(11) NULL DEFAULT NULL,
  `empleado_idempleado` INT(11) NOT NULL,
  `supervisor_idempleado` INT(11) NOT NULL,
  `encargado_idempleado` INT(11) NOT NULL,
  `paquete_idpaquete` INT(11) NOT NULL,
  PRIMARY KEY (`idlavado`),
  INDEX `fk_lavado_empleado_idx` (`empleado_idempleado` ASC),
  INDEX `fk_lavado_empleado1_idx` (`supervisor_idempleado` ASC),
  INDEX `fk_lavado_empleado2_idx` (`encargado_idempleado` ASC),
  INDEX `fk_lavado_paquete1_idx` (`paquete_idpaquete` ASC),
  CONSTRAINT `fk_lavado_empleado`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `is`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lavado_empleado1`
    FOREIGN KEY (`supervisor_idempleado`)
    REFERENCES `is`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lavado_empleado2`
    FOREIGN KEY (`encargado_idempleado`)
    REFERENCES `is`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lavado_paquete1`
    FOREIGN KEY (`paquete_idpaquete`)
    REFERENCES `is`.`paquete` (`idpaquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `is`.`lavado_has_articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is`.`lavado_has_articulo` (
  `lavado_idlavado` INT(11) NOT NULL,
  `articulo_idarticulo` INT(11) NOT NULL,
  PRIMARY KEY (`lavado_idlavado`, `articulo_idarticulo`),
  INDEX `fk_lavado_has_articulo_articulo1_idx` (`articulo_idarticulo` ASC),
  INDEX `fk_lavado_has_articulo_lavado1_idx` (`lavado_idlavado` ASC),
  CONSTRAINT `fk_lavado_has_articulo_articulo1`
    FOREIGN KEY (`articulo_idarticulo`)
    REFERENCES `is`.`articulo` (`idarticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lavado_has_articulo_lavado1`
    FOREIGN KEY (`lavado_idlavado`)
    REFERENCES `is`.`lavado` (`idlavado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
